# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PiSurvl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PiSurvl
  pod 'Google/SignIn'
  pod 'GoogleAPIClientForREST/Drive'
  pod 'SwiftyJSON'

  target 'PiSurvlTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
